default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: solidus-on-heroku

test:
  <<: *default
  database: solidus-on-heroku-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
